branches:
    - label: enhancement
      prefix: 'feature/'
    - label: bug
      prefix: 'fix/'
    - label: change
      prefix: 'feature/'
    - label: '*'
      skip: true
branchName: '${issue.title[0, 45]}'
commentMessage: 'Branch `${branchName}` created for issue: `${issue.title}`'
autoCloseIssue: true
