name: changeVersion

on: push

# on: 
#   push:
#     branches:
#      - beta
#      - main

jobs: 
  changeVersion: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install 
      - run: pwd  
      - run: ls -la  
      #   uses: juliangruber/read-file-action@v1
      #   with: 
      #     path: ./package.json

      # - name: echo version
      #   run: echo "${{ steps.package.outputs.content }}"
