name: changeVersion

on: push

# on: 
#   push:
#     branches:
#      - beta
#      - main

jobs: 
  changeVersion: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install 

      - name: read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: echo file
        run: echo -e ${{steps.version.outputs.content}} + 1 > ./VERSION
