name: changeVersion

on: push

# on: 
#   push:
#     branches:
#      - beta
#      - main

jobs: 
  changeVersion: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install 

      - name: echo version
        env: 
          VERSION: ${{ secrets.VERSION }}
        run: echo ${{ secrets.VERSION }}