name: Deployment
# on:
#     push:
#         branches:
#             - main

# Jobs to run
jobs:
    # Build the bot job,
    build-bot:
        # Run it on ubuntu
        runs-on: ubuntu-latest

        # Steps of the job
        steps:
            # Checkout the repo at the current state
            - uses: actions/checkout@v3

              # Login to the GitHub Container Registry
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              # Build and Push the bot to the GHCR
            - name: Build and Push to GHCR
              run: |
                  docker build . --tag ghcr.io/AccountUsername/RepoName:latest
                  docker push ghcr.io/AccountUsername/RepoName:latest