name: Deployment BETA

on:
    push:
        branches:
            - beta

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install --omit=dev

            - name: Get production data
              run: |
                  touch .env
                  echo "$PRODUCTION_ENV" > .env
                  echo "$PRODUCTION_DOCKER" > docker-compose.override.yml

            - name: Build
              run: |
                  npm run restart-prod
