name: Deployment BETA

on:
    push:
        branches:
            - beta

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install --omit=dev

            - name: Get production files
              run: |
                  cp ../.env .env
                  cp ../docker-compose.override.yml docker-compose.override.yml
                  cp ../Dockerfile.prod Dockerfile.prod

            - name: Build
              run: |
                  npm run restart-prod
