name: Deployment BETA

on:
    push:
        branches:
            - beta
            - dev

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set working directory
              run: |
                echo "::set-env name=WORKING_DIRECTORY::${{ secrets.BETA_PATH }}"
            
            - name: Use working directory
              run: |
                cd $WORKING_DIRECTORY

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            # - name: Load environment variables
            #   run: |
            #     echo "Loading environment variables from .env file"
            #     source .env

            - name: Show Files
              run: |
                  ls -la
                  pwd

            - name: Install dependencies
              run: npm install --production

            - name: Build
              run: npm run restart
