name: Release Drafter

on:
    push:
        branches:
            - main
            - beta

permissions:
    contents: read

jobs:
    update_release_draft:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'

            - name: Extract version from package.json
              id: extract-version
              run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

            - name: Release Drafter
              uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  config-path: .github/release-drafter.yml
                  tag: ${{ github.ref }}
