name: 'First interaction'
description: 'Greet new contributors when they create their first issue or open their first pull request'
author: 'Mittelbot Github Bot'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  issue-message:
    description: 'Hello! As i see is this your first issue. Please make sure to explain your issue or request as detailed as possible.\n If you''re done you have to wait :)'
  pr-message:
    description: 'Hello! As i see is this your first pull request. First take a look at the Github actions if they have passed successfully. If not, check your code and try again.\n A Developer will look into it as soon as possible.'
runs:
  using: 'docker'
  image: 'Dockerfile'