name: Deployment Test Build

on:
    pull_request:
        branches: [dev, main, beta]

jobs:
    test-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install test env data
              run: |
                  cp .env.example .env
                  echo ${{ secrets.TEST_TOKEN }} >> .env
                  echo ${{ secrets.TEST_TOKEN }} >> .env
                  echo ${{ secrets.TEST_SECRET }} >> .env
                  echo ${{ secrets.TEST_APPLICATION_ID }} >> .env
                  echo ${{ secrets.TEST_DEVELOPER_DISCORD_GUILD_ID }} >> .env

            - name: Start Container
              run: |
                  NODE_ENV=production docker compose up -d

            - name: Wait 60 seconds and check if all containers are healthy without any npm commands
              run: |
                  sleep 60
                  docker ps -a                  
                  docker inspect --format='{{json .State.Health}}' mittelbot
                  docker inspect --format='{{json .State.Health}}' mittelbot-mysql

            - name: Stop Container
              run: |
                  npm run stop

            - name: Stop Workflow
              if: steps.check_condition.outputs.stop_workflow == 'true'
              run: |
                  echo "Stopping workflow"
                  exit 0
