name: Deployment Test Build

on:
    pull_request:
        branches: [dev, main, beta]

jobs:
    test-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install test env data
              run: |
                  cp .env.example .env
                  echo "NODE_ENV=production" >> .env
                  echo ${{ secrets.TEST_TOKEN }} >> .env
                  echo ${{ secrets.TEST_TOKEN }} >> .env
                  echo ${{ secrets.TEST_SECRET }} >> .env
                  echo ${{ secrets.TEST_APPLICATION_ID }} >> .env
                  echo ${{ secrets.TEST_DEVELOPER_DISCORD_GUILD_ID }} >> .env
                  echo ${{ secrets.TEST_APPLICATION_ID }}

            - name: Install important data
              run: |
                  npm run start

            - name: Wait 10 seconds and check if all containers are healthy without any npm commands
              run: |
                  sleep 10
                  docker ps -a
                  docker inspect --format='{{json .State.Health.Status}}' $(docker ps -aq) | grep -v healthy | wc -l
                  

            - name: Stop Container
              run: |
                  npm run stop

            - name: Stop Workflow
              if: steps.check_condition.outputs.stop_workflow == 'true'
              run: |
                  echo "Stopping workflow"
                  exit 0
